version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true

  backend:
    build:
      context: ./backend
    ports:
      - "10000:10000"
